name: ADM Remediation Verify
on: [workflow_dispatch]
jobs:
  build:
    name: Build HelloWorld native-image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Build 
        run: |
          mvn package test

      - name: Upload JSON files
        uses: actions/upload-artifact@v2
        with:
          name: build JSON
          path: target/NativeHelloWorld.*.json
